# this handling of mDNSResponder stub resolvers should eventually go to
# data-utilities to be reusable
- name: create resolver directory (Darwin)
  ansible.builtin.file:
    path: /etc/resolver
    state: directory
    owner: root
    group: wheel

- name: add stub resolvers
  template:
    src: macos-resolver.j2
    dest: "/etc/resolver/{{stub_zone.value['name']}}"
    owner: "{{_unbound_new_conf_user|default('root')}}"
    group: "{{_unbound_new_conf_group|default('root')}}"
    mode: 0644
  loop_control:
    loop_var: stub_zone
  with_dict: "{{unbound_stub_zones|default(unbound.stub_zones)}}"
  vars:
    stub_resolver: 127.0.0.1
  register: _darwin_stubs
  when: >
    (unbound.stub_zones is defined or
     unbound_stub_zones is defined)

- name: reload mDNSResponder
  shell: killall -HUP mDNSResponder
  when: _darwin_stubs is changed
