# this handling of mDNSResponder stub resolvers should eventually go to
# data-utilities to be reusable
- name: create resolver directory (Darwin)
  ansible.builtin.file:
    path: "{{config_prefix}}/etc/resolver"
    state: directory
    owner: {{_unbound_user}}
    group: {{_unbound_group}}

- name: add stub resolvers
  template:
    src: macos-resolver.j2
    dest: "{{config_prefix}}/etc/resolver/{{stub_zone.value['name']}}"
    owner: {{_unbound_user}}
    group: {{_unbound_group}}
    mode: 0644
  loop_control:
    loop_var: stub_zone
  with_dict: "{{unbound_stub_zones|default(unbound.stub_zones)}}"
  vars:
    stub_resolver: 127.0.0.1
  register: _darwin_stubs
  when: >
    (unbound.stub_zones is defined or
     unbound_stub_zones is defined)

- name: reload mDNSResponder
  shell: killall -HUP mDNSResponder
  when: >
    _darwin_stubs is changed and
    _config_only == false
