- set_fact:
    _config_only: false

- set_fact:
    _config_only: true
  when: >
    ansible_connection == "local"

- set_fact:
    config_prefix: ""
  when: config_prefix is undefined

- set_fact:
    _unbound_user: root
  when: _unbound_user is undefined

- set_fact:
    _unbound_group: root
  when: >
    _unbound_group is undefined and
    ansible_os_family != "Darwin"

- set_fact:
    _unbound_group: wheel
  when: >
    _unbound_group is undefined and
    ansible_os_family == "Darwin"

- set_fact:
    role_packages:
      - unbound
  when: _config_only == false

- set_fact:
    _unbound_prefix: /usr
    _unbound_conf_prefix: "{{unbound.core.directory|default('/etc/unbound')}}"

- set_fact:
    _unbound_prefix: "{{homebrew_prefix}}"
    _unbound_conf_prefix: "{{unbound.core.directory|default(homebrew_prefix+'/etc/unbound')}}"
  when: >
    ansible_os_family == "Darwin"

- set_fact:
    _unbound_home: "/var/unbound"
  when: >
    ansible_os_family == "Darwin"

- include_role:
    name: data-utilities
    tasks_from: install_packages
  when: _config_only == false

- name: add groups (Darwin)
  group:
    name: "{{_unbound_group}}"
    system: yes
  when: >
    ansible_os_family == "Darwin" and
    _config_only == false

- name: add user (Darwin)
  user:
    name: "{{_unbound_user}}"
    group: "{{_unbound_group}}"
    createhome: yes
    home: "{{_unbound_home}}"
    system: yes
  when: >
    ansible_os_family == "Darwin" and
    _config_only == false

- name: Mask unbound service to disable trust anchor (RedHat), directory
  file:
    state: directory
    path: "{{config_prefix}}/etc/systemd/system"
    mode: 0755
    owner: "{{_unbound_user}}"
    group: "{{_unbound_group}}"
  when: >
    ansible_os_family != "Darwin"

# RedHat has a hard coded call to unbound-anchor in the service file
# Without being able to update that it blocks startup for almost a minute.
- name: Mask unbound service to disable trust anchor (RedHat), file
  copy:
    src: unbound.service
    dest: "{{config_prefix}}/etc/systemd/system/unbound.service"
    owner: "{{_unbound_user}}"
    group: "{{_unbound_group}}"
    mode: 0644
  notify:
    - restart unbound
  when: >
    ansible_os_family != "Darwin"

- name: update unbound configuration, directory
  file:
    state: directory
    dest: "{{config_prefix}}{{_unbound_conf_prefix}}"
    mode: 0755
    owner: "{{_unbound_user}}"
    group: "{{_unbound_group}}"

- name: update unbound configuration, file
  template:
    src: unbound.conf.j2
    dest: "{{config_prefix}}{{_unbound_conf_prefix}}/unbound.conf.new"
    owner: "{{_unbound_user}}"
    group: "{{_unbound_group}}"
    mode: 0644
  register: status

- name: verify unbound configuration
  shell: "{{_unbound_prefix}}/sbin/unbound-checkconf  {{config_prefix}}{{_unbound_conf_prefix}}/unbound.conf.new"
  when: status is changed and _config_only == false

- name: update unbound configuration
  copy:
    src: "{{config_prefix}}{{_unbound_conf_prefix}}/unbound.conf.new"
    dest: "{{config_prefix}}{{_unbound_conf_prefix}}/unbound.conf"
    owner: "{{_unbound_user}}"
    group: "{{_unbound_group}}"
    mode: 0644
    remote_src: yes
  notify:
    - restart unbound
  when: >
    status is changed

- name: configure firewall
  firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: true
  when: >
    _config_only == false and
    ansible_os_family == "RedHat" or
    (firewalld_available is defined and
    firewalld_available == True)

- name: add stub resolvers (Darwin)
  include_tasks: darwin_stub_zones.yml
  when: >
    ansible_os_family == "Darwin" and
    (unbound.stub_zones is defined or
     unbound_stub_zones is defined)

- name: enable unbound
  service: name=unbound enabled=yes
  when: >
    _config_only == false and
    ansible_os_family != "Darwin"

# for darwin the service needs to get created first, so easier to go through
# the service include
- name: start and enable unbound (Darwin)
  include_role:
    name: data-utilities
    tasks_from: manage_service
  vars:
    service:
      name: "{{_unbound_service|default('fi.aardsoft.unbound')}}"
      exec_start: "{{_unbound_prefix}}/sbin/unbound -d -c {{_unbound_new_conf|default(_unbound_conf_prefix+'/unbound.conf.new')}}"
      user: "{{_unbound_user|default('root')}}"
      standard_output: "{{_unbound_home}}/log.out"
      standard_error: "{{_unbound_home}}/log.err"
      working_directory: "{{_unbound_home}}"
  when: >
    _config_only == false and
    ansible_os_family == "Darwin"
