- set_fact:
    role_packages:
      - unbound

- include_role:
    name: basic-host
    tasks_from: install_packages

# RedHat has a hard coded call to unbound-anchor in the service file
# Without being able to update that it blocks startup for almost a minute.
- name: Mask unbound service to disable trust anchor (RedHat)
  copy:
    src: unbound.service
    dest: /etc/systemd/system/unbound.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart unbound

- name: update unbound configuration
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.new
    owner: root
    group: root
    mode: 0644
  register: status
  notify:
    - restart unbound

- name: verify unbound configuration
  shell: /usr/sbin/unbound-checkconf /etc/unbound/unbound.conf.new
  when: status is changed

- name: update unbound configuration
  copy:
    src: /etc/unbound/unbound.conf.new
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  when: status is changed
  notify:
    - restart unbound

- name: configure firewall
  firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: true
  when: >
    ansible_os_family == "RedHat" or
    (firewalld_available is defined and
    firewalld_available == True)

- name: enable unbound
  service: name=unbound enabled=yes